show_cart:
    pattern:   /show_cart
    defaults:  { _controller: CartBundle:Cart:show_cart }
    requirements:
        _method:  GET

to_cart:
    pattern:   /to_cart/
    defaults:  { _controller: CartBundle:Cart:to_cart }
    requirements:
        _method:  POST