<?php

namespace InstantSoin\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class userRepository extends EntityRepository
{
	public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT nom FROM UserBundle:User nom ORDER BY nom.nom ASC'
            )
            ->getResult();
    }
}
