product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Accueil:accueil }


product_overall:
    path:     /products_overall
    defaults: { _controller: ProductBundle:Products:products_overall }


services_overall:
    path:     /services_overall
    defaults: { _controller: ProductBundle:Services:services_overall }

equipment_overall:
    path:     /equipment_overall
    defaults: { _controller: ProductBundle:Equipment:equipment_overall }

Demande_contact:
    path:     /
    defaults: { _controller: ProductBundle:Accueil:accueil }


Accueil_sidebar:
    pattern:  /sidebar
    defaults: { _controller: ProductBundle:Accueil:sidebar }
    requirements:
        _method:  GET

whoswho:
    pattern:  /whoswho
    defaults: { _controller: ProductBundle:Accueil:whoswho }
    requirements:
        _method:  GET

Lien_Clairjoie:
    pattern:  /clairjoie
    defaults: { _controller: ProductBundle:Accueil:clairjoie }

Lien_Cnd_shellac:
    pattern:  /cnd_shellac
    defaults: { _controller: ProductBundle:Accueil:cnd_shellac }