product_homepage:
    path:     /
    defaults: { _controller: ProductBundle:Accueil:accueil }


#ROUTING PRODUCTS

product_overall:
    path:     /products_overall
    defaults: { _controller: ProductBundle:Products:products_overall }

products_by_cat:
    path:     /products_by_cat/{id}
    defaults: { _controller: ProductBundle:Products:products_by_cat }
    requirements:
        _method:  GET|POST

#ROUTING SERVICES

services_overall:
    path:     /services_overall
    defaults: { _controller: ProductBundle:Services:services_overall }

services_by_cat:
    path:     /services_by_cat/{id}
    defaults: { _controller: ProductBundle:Services:services_by_cat }
    requirements:
        _method:  GET|POST






Demande_contact:
    path:     /contact
    defaults: { _controller: UserBundle:Security:contact }


Accueil_sidebar:
    pattern:  /sidebar
    defaults: { _controller: ProductBundle:Accueil:sidebar }
    requirements:
        _method:  GET



whoswho:
    pattern:  /whoswho
    defaults: { _controller: ProductBundle:Accueil:whoswho }
    requirements:
        _method:  GET

Lien_Clairjoie:
    pattern:  /clairjoie
    defaults: { _controller: ProductBundle:Accueil:clairjoie }

Lien_Cnd_shellac:
    pattern:  /cnd_shellac
    defaults: { _controller: ProductBundle:Accueil:cnd_shellac }

# -------------------------------------------------------------------------------------- #
# ------------ GESTION DES PRODUITS / CATEGORIES / FOURNISSEURS / SERVICES : ----------- #
# -------------------------------------------------------------------------------------- #



# ----------------------------------- CATEGORIES PROD ---------------------------------- #
createCategoryProd:
    pattern:  /createCategoryProd
    defaults: { _controller: ProductBundle:CategoryProdAdmin:createCategoryProd }
    requirements:
        _method:  GET|POST


updateCategoryProd:
    pattern:  /updateCategoryProd/{id}
    defaults: { _controller: ProductBundle:CategoryProdAdmin:updateCategoryProd }
    requirements:
        _method:  GET|POST


deleteCategoryProd:
    pattern:  /deleteCategoryProd/{id}
    defaults: { _controller: ProductBundle:CategoryProdAdmin:deleteCategoryProd }
    requirements:
        _method:  GET|POST


listingCategoryProd:
    pattern:  /listingCategoryProd
    defaults: { _controller: ProductBundle:CategoryProdAdmin:listingCategoryProd }
    requirements:
        _method:  GET|POST



# ----------------------------------- CATEGORIES SERV ---------------------------------- #
createCategoryServ:
    pattern:  /createCategoryServ
    defaults: { _controller: ProductBundle:CategoryServAdmin:createCategoryServ }
    requirements:
        _method:  GET|POST


updateCategoryServ:
    pattern:  /updateCategoryServ/{id}
    defaults: { _controller: ProductBundle:CategoryServAdmin:updateCategoryServ }
    requirements:
        _method:  GET|POST


deleteCategoryServ:
    pattern:  /deleteCategoryServ/{id}
    defaults: { _controller: ProductBundle:CategoryServAdmin:deleteCategoryServ }
    requirements:
        _method:  GET|POST


listingCategoryServ:
    pattern:  /listingCategoryServ
    defaults: { _controller: ProductBundle:CategoryServAdmin:listingCategoryServ }
    requirements:
        _method:  GET|POST




# ------------------------------------ SUPPLIERS ------------------------------------ #
createSupplier:
    pattern:  /createSupplier
    defaults: { _controller: ProductBundle:SupplierAdmin:createSupplier }
    requirements:
        _method:  GET|POST


updateSupplier:
    pattern:  /updateSupplier/{id}
    defaults: { _controller: ProductBundle:SupplierAdmin:updateSupplier }
    requirements:
        _method:  GET|POST


deleteSupplier:
    pattern:  /deleteSupplier/{id}
    defaults: { _controller: ProductBundle:SupplierAdmin:deleteSupplier }
    requirements:
        _method:  GET|POST


listingSupplier:
    pattern:  /listingSupplier
    defaults: { _controller: ProductBundle:SupplierAdmin:listingSupplier }
    requirements:
        _method:  GET|POST



# ------------------------------------ SERVICES ------------------------------------ #
createServices:
    pattern:  /createServices
    defaults: { _controller: ProductBundle:ServicesAdmin:createServices }
    requirements:
        _method:  GET|POST


updateServices:
    pattern:  /updateServices/{id}
    defaults: { _controller: ProductBundle:ServicesAdmin:updateServices }
    requirements:
        _method:  GET|POST


deleteServices:
    pattern:  /deleteServices/{id}
    defaults: { _controller: ProductBundle:ServicesAdmin:deleteServices }
    requirements:
        _method:  GET|POST


listingServices:
    pattern:  /listingServices
    defaults: { _controller: ProductBundle:ServicesAdmin:listingServices }
    requirements:
        _method:  GET|POST



# ------------------------------------ PRODUCTS ------------------------------------ #
createProducts:
    pattern:  /createProducts
    defaults: { _controller: ProductBundle:ProductsAdmin:createProducts }
    requirements:
        _method:  GET|POST


updateProducts:
    pattern:  /updateProducts/{id}
    defaults: { _controller: ProductBundle:ProductsAdmin:updateProducts }
    requirements:
        _method:  GET|POST


deleteProducts:
    pattern:  /deleteProducts/{id}
    defaults: { _controller: ProductBundle:ProductsAdmin:deleteProducts }
    requirements:
        _method:  GET|POST


listingProducts:
    pattern:  /listingProducts
    defaults: { _controller: ProductBundle:ProductsAdmin:listingProducts }
    requirements:
        _method:  GET|POST