login:
   pattern:   /login
   defaults:  { _controller: UserBundle:Security:login }

login_check:
   pattern:   /login_check

logout:
  pattern:    /logout

admin:
  pattern:    /admin
  defaults:   { _controller: UserBundle:Admin:admin }

estheticienne:
  pattern:    /estheticienne
  defaults:   { _controller: UserBundle:Estheticienne:estheticienne }

user_profil:
  path:     /user_profil
  defaults: { _controller: UserBundle:Security:profil }


profil_info:
  path:     /profil_info/{username}
  defaults: { _controller: UserBundle:Security:profil_info }


listingCustomer:
  path:     /listingCustomer/
  defaults: { _controller: UserBundle:Security:listingCustomer }


updateCustomer:
  path:     /updateCustomer/{id}
  defaults: { _controller: UserBundle:Security:updateCustomer }

deleteCustomer:
  path:     /deleteCustomer/{id}
  defaults: { _controller: UserBundle:Security:deleteCustomer }


new_account:
    path:     /new_account
    defaults: { _controller: UserBundle:Security:new_account }

new_account_admin:
    path:     /new_account_admin
    defaults: { _controller: UserBundle:Security:new_account_admin }

sidebar_estheticienne:
    pattern:  /sidebar_estheticienne
    defaults: { _controller: UserBundle:Estheticienne:sidebar_estheticienne }
    requirements:
        _method:  GET

sidebar_admin:
    pattern:  /sidebar_admin
    defaults: { _controller: UserBundle:Admin:sidebar_admin }
    requirements:
        _method:  GET

