cart_view:
    path:     /cart/
    defaults: { _controller: OrderBundle:Cart:Cart }


to_cart:
    pattern:  /to_cart/
    defaults: { _controller: OrderBundle:Cart:to_cart }
    requirements:
        _method:  POST

emptyCart:
    pattern:  /emptyCart/
    defaults: { _controller: OrderBundle:Cart:emptyCart }
    requirements:
        _method:  POST

modify_cart:
    pattern:  /modify_cart/
    defaults: { _controller: OrderBundle:Cart:modify_cart }
    requirements:
        _method:  POST

del_prod_cart:
    pattern:  /del_prod_cart/{id}
    defaults: { _controller: OrderBundle:Cart:del_prod_cart }
    requirements:
        _method:  GET