services:
#    order.example:
#        class: InstantSoin\OrderBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
tva:
  class: InstantSoin\ProductBundle\Twig\Extension\TvaExtension
  tags:
    - { name: twig.extension }

montantTva:
  class: InstantSoin\ProductBundle\Twig\Extension\MontantTvaExtension
  tags:
    - { name: twig.extension }